service: pardos-chicken-orders
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::572536330236:role/voclabs   # usa tu rol existente

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pardos-orders
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    PardosEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: pardos-bus

    EvidenceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pardos-evidence
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

functions:
  createOrder:
    handler: src/orders/create.handler
    events:
      - httpApi:
          path: /orders
          method: POST

  getOrder:
    handler: src/orders/get.handler
    events:
      - httpApi:
          path: /orders/{orderId}
          method: GET

  kitchenStart:
    handler: src/kitchen/start.handler
    events:
      - httpApi:
          path: /kitchen/{orderId}/start
          method: POST

  kitchenComplete:
    handler: src/kitchen/complete.handler
    events:
      - httpApi:
          path: /kitchen/{orderId}/complete
          method: POST

  packingComplete:
    handler: src/packing/complete.handler
    events:
      - httpApi:
          path: /packing/{orderId}/complete
          method: POST

  assignDriver:
    handler: src/delivery/assign.handler
    events:
      - httpApi:
          path: /delivery/{orderId}/assign
          method: POST

  orderDelivered:
    handler: src/delivery/delivered.handler
    events:
      - httpApi:
          path: /delivery/{orderId}/delivered
          method: POST

  listByStatus:
    handler: src/dashboard/listByStatus.handler
    events:
      - httpApi:
          path: /dashboard
          method: GET
